<?php

use Illuminate\Database\Seeder;

class LanguagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("INSERT INTO `languages` (`id`, `code`, `name`) VALUES
            (1, 'aa', 'Afar'),
            (2, 'ab', 'Abkhazian'),
            (3, 'af', 'Afrikaans'),
            (4, 'ak', 'Akan'),
            (5, 'sq', 'Albanian'),
            (6, 'am', 'Amharic'),
            (7, 'ar', 'Arabic'),
            (8, 'an', 'Aragonese'),
            (9, 'hy', 'Armenian'),
            (10, 'as', 'Assamese'),
            (11, 'av', 'Avaric'),
            (12, 'ae', 'Avestan'),
            (13, 'ay', 'Aymara'),
            (14, 'az', 'Azerbaijani'),
            (15, 'ba', 'Bashkir'),
            (16, 'bm', 'Bambara'),
            (17, 'eu', 'Basque'),
            (18, 'be', 'Belarusian'),
            (19, 'bn', 'Bengali'),
            (20, 'bh', 'Bihari languages'),
            (21, 'bi', 'Bislama'),
            (22, 'bs', 'Bosnian'),
            (23, 'br', 'Breton'),
            (24, 'bg', 'Bulgarian'),
            (25, 'my', 'Burmese'),
            (26, 'ca', 'Catalan; Valencian'),
            (27, 'ch', 'Chamorro'),
            (28, 'ce', 'Chechen'),
            (29, 'zh', 'Chinese'),
            (30, 'cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
            (31, 'cv', 'Chuvash'),
            (32, 'kw', 'Cornish'),
            (33, 'co', 'Corsican'),
            (34, 'cr', 'Cree'),
            (35, 'cs', 'Czech'),
            (36, 'da', 'Danish'),
            (37, 'dv', 'Divehi; Dhivehi; Maldivian'),
            (38, 'nl', 'Dutch; Flemish'),
            (39, 'dz', 'Dzongkha'),
            (40, 'en', 'English'),
            (41, 'eo', 'Esperanto'),
            (42, 'et', 'Estonian'),
            (43, 'ee', 'Ewe'),
            (44, 'fo', 'Faroese'),
            (45, 'fj', 'Fijian'),
            (46, 'fi', 'Finnish'),
            (47, 'fr', 'French'),
            (48, 'fy', 'Western Frisian'),
            (49, 'ff', 'Fulah'),
            (50, 'ka', 'Georgian'),
            (51, 'de', 'German'),
            (52, 'gd', 'Gaelic; Scottish Gaelic'),
            (53, 'ga', 'Irish'),
            (54, 'gl', 'Galician'),
            (55, 'gv', 'Manx'),
            (56, 'el', 'Greek, Modern (1453-)'),
            (57, 'gn', 'Guarani'),
            (58, 'gu', 'Gujarati'),
            (59, 'ht', 'Haitian; Haitian Creole'),
            (60, 'ha', 'Hausa'),
            (61, 'he', 'Hebrew'),
            (62, 'hz', 'Herero'),
            (63, 'hi', 'Hindi'),
            (64, 'ho', 'Hiri Motu'),
            (65, 'hr', 'Croatian'),
            (66, 'hu', 'Hungarian'),
            (67, 'ig', 'Igbo'),
            (68, 'is', 'Icelandic'),
            (69, 'io', 'Ido'),
            (70, 'ii', 'Sichuan Yi; Nuosu'),
            (71, 'iu', 'Inuktitut'),
            (72, 'ie', 'Interlingue; Occidental'),
            (73, 'ia', 'Interlingua (International Auxiliary Language Association)'),
            (74, 'id', 'Indonesian'),
            (75, 'ik', 'Inupiaq'),
            (76, 'it', 'Italian'),
            (77, 'jv', 'Javanese'),
            (78, 'ja', 'Japanese'),
            (79, 'kl', 'Kalaallisut; Greenlandic'),
            (80, 'kn', 'Kannada'),
            (81, 'ks', 'Kashmiri'),
            (82, 'kr', 'Kanuri'),
            (83, 'kk', 'Kazakh'),
            (84, 'km', 'Central Khmer'),
            (85, 'ki', 'Kikuyu; Gikuyu'),
            (86, 'rw', 'Kinyarwanda'),
            (87, 'ky', 'Kirghiz; Kyrgyz'),
            (88, 'kv', 'Komi'),
            (89, 'kg', 'Kongo'),
            (90, 'ko', 'Korean'),
            (91, 'kj', 'Kuanyama; Kwanyama'),
            (92, 'ku', 'Kurdish'),
            (93, 'lo', 'Lao'),
            (94, 'la', 'Latin'),
            (95, 'lv', 'Latvian'),
            (96, 'li', 'Limburgan; Limburger; Limburgish'),
            (97, 'ln', 'Lingala'),
            (98, 'lt', 'Lithuanian'),
            (99, 'lb', 'Luxembourgish; Letzeburgesch'),
            (100, 'lu', 'Luba-Katanga'),
            (101, 'lg', 'Ganda'),
            (102, 'mk', 'Macedonian'),
            (103, 'mh', 'Marshallese'),
            (104, 'ml', 'Malayalam'),
            (105, 'mi', 'Maori'),
            (106, 'mr', 'Marathi'),
            (107, 'ms', 'Malay'),
            (108, 'mg', 'Malagasy'),
            (109, 'mt', 'Maltese'),
            (110, 'mn', 'Mongolian'),
            (111, 'na', 'Nauru'),
            (112, 'nv', 'Navajo; Navaho'),
            (113, 'nr', 'Ndebele, South; South Ndebele'),
            (114, 'nd', 'Ndebele, North; North Ndebele'),
            (115, 'ng', 'Ndonga'),
            (116, 'ne', 'Nepali'),
            (117, 'nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
            (118, 'nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
            (119, 'no', 'Norwegian'),
            (120, 'ny', 'Chichewa; Chewa; Nyanja'),
            (121, 'oc', 'Occitan (post 1500); Provençal'),
            (122, 'oj', 'Ojibwa'),
            (123, 'or', 'Oriya'),
            (124, 'om', 'Oromo'),
            (125, 'os', 'Ossetian; Ossetic'),
            (126, 'pa', 'Panjabi; Punjabi'),
            (127, 'fa', 'Persian'),
            (128, 'pi', 'Pali'),
            (129, 'pl', 'Polish'),
            (130, 'pt', 'Portuguese'),
            (131, 'ps', 'Pushto; Pashto'),
            (132, 'qu', 'Quechua'),
            (133, 'rm', 'Romansh'),
            (134, 'ro', 'Romanian; Moldavian; Moldovan'),
            (135, 'rn', 'Rundi'),
            (136, 'ru', 'Russian'),
            (137, 'sg', 'Sango'),
            (138, 'sa', 'Sanskrit'),
            (139, 'si', 'Sinhala; Sinhalese'),
            (140, 'sk', 'Slovak'),
            (141, 'sl', 'Slovenian'),
            (142, 'se', 'Northern Sami'),
            (143, 'sm', 'Samoan'),
            (144, 'sn', 'Shona'),
            (145, 'sd', 'Sindhi'),
            (146, 'so', 'Somali'),
            (147, 'st', 'Sotho, Southern'),
            (148, 'es', 'Spanish; Castilian'),
            (149, 'sc', 'Sardinian'),
            (150, 'sr', 'Serbian'),
            (151, 'ss', 'Swati'),
            (152, 'su', 'Sundanese'),
            (153, 'sw', 'Swahili'),
            (154, 'sv', 'Swedish'),
            (155, 'ty', 'Tahitian'),
            (156, 'ta', 'Tamil'),
            (157, 'tt', 'Tatar'),
            (158, 'te', 'Telugu'),
            (159, 'tg', 'Tajik'),
            (160, 'tl', 'Tagalog'),
            (161, 'th', 'Thai'),
            (162, 'bo', 'Tibetan'),
            (163, 'ti', 'Tigrinya'),
            (164, 'to', 'Tonga (Tonga Islands)'),
            (165, 'tn', 'Tswana'),
            (166, 'ts', 'Tsonga'),
            (167, 'tk', 'Turkmen'),
            (168, 'tr', 'Turkish'),
            (169, 'tw', 'Twi'),
            (170, 'ug', 'Uighur; Uyghur'),
            (171, 'uk', 'Ukrainian'),
            (172, 'ur', 'Urdu'),
            (173, 'uz', 'Uzbek'),
            (174, 've', 'Venda'),
            (175, 'vi', 'Vietnamese'),
            (176, 'vo', 'Volapük'),
            (177, 'cy', 'Welsh'),
            (178, 'wa', 'Walloon'),
            (179, 'wo', 'Wolof'),
            (180, 'xh', 'Xhosa'),
            (181, 'yi', 'Yiddish'),
            (182, 'yo', 'Yoruba'),
            (183, 'za', 'Zhuang; Chuang'),
            (184, 'zu', 'Zulu');
        ");
    }
}
